default:
    method: "sac"
    max_steps: 200
    max_frames: 10000
    frame_skip: 2
    policy_lr: !!float 3e-3
    value_lr: !!float 3e-4
    soft_q_lr: !!float 3e-4
    reward_scale: 1.0
    activation_fun: 'ReLU'

PendulumEnv:
    activation_fun: 'ReLU'
    max_frames: 10000
    frame_skip: 1
    max_steps: 200

AcrobotEnv:
    activation_fun: 'ReLU'
    max_frames: 10000
    frame_skip: 1
    max_steps: 500

PendubotEnv:
    activation_fun: 'ReLU'
    max_frames: 10000
    frame_skip: 2
    max_steps: 500

InvertedPendulumBulletEnv:
    activation_fun: 'sin'
    max_frames: 10000
    frame_skip: 4
    max_steps: 200

InvertedPendulumRoboschoolEnv:
    activation_fun: 'ReLU'
    max_frames: 50000
    frame_skip: 1
    max_steps: 1000

HopperEnv:
    activation_fun: 'ReLU'
    max_frames: 50000
    max_steps: 1000
    frame_skip: 1

HalfCheetahEnv:
    activation_fun: 'ReLU'
    max_frames: 50000
    max_steps: 1000
    frame_skip: 5

PusherEnv:
    activation_fun: 'ReLU'
    max_frames: 50000
    max_steps: 100
    frame_skip: 1
